name: 'MCReleaser'
description: 'A program to publish artifacts to multiple Minecraft-related platforms'
inputs:
  files:
    description: 'The files to upload'
    required: true
  platforms:
    description: 'The platforms to upload to'
    required: false
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DOCKER_FILES: ${{ inputs.files }}
    DOCKER_PLATFORMS: ${{ inputs.platforms }}
