name: 'MCReleaser'
description: 'A program to publish artifacts to multiple Minecraft-related platforms'
inputs:
  files:
    description: 'The files to upload'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DOCKER_FILES: ${{ inputs.files }}
